name: Channel Map ETL 

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: rir-tracking

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      
      - name: Run ETL Process
        id: etl
        run: |
          go run ./cmd/etl/main.go

      - name: Update Tracking Issue 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ steps.etl.outcome }}" == "failure" ]; then
            MESSAGE="💥 failure"
          elif [ -f ./channel-map.gz ]; then
            MESSAGE="🟢 update produced"
            mv channel-map.gz ./internal/channel/data/channel-map.gz
          else
            MESSAGE="🔴 no update"
          fi
          gh issue comment 1 --body "$(date -u '+%Y-%m-%d') $MESSAGE"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update channel map"
          file_pattern: ./internal/channel/data/channel-map.gz
          branch: rir-tracking